In [6]:
import datetime as dt

In [8]:
dateobj = dt.datetime.strptime("12/10/2019 12:15:13 AM", "%m/%d/%Y %I:%M:%S %p")
tm = int(dateobj.timestamp())
print(tm)

1575954913


In [25]:
import math
INTERVAL = 600
SLOTS_PER_DAY = 24 * 60 * 60 / INTERVAL

x0 = 1575954913
x1 = 1576817761
offset = (x0 // INTERVAL) * INTERVAL
print(offset)
i0 = (x0 - offset) // INTERVAL
len = (x1 - offset) // INTERVAL

len_aligned = int(math.ceil(len / SLOTS_PER_DAY)*SLOTS_PER_DAY)
print(i0, len, len_aligned)

1575954600
0 1438 1440


1440

In [1]:
import numpy as np

In [16]:
x = [list(range(6)) for x in range(4)]
y = [list(range(6)) for x in range(4)]

In [17]:
def root_mean_squared_error(y, t):
    l2 = []
    for x in zip(y,t):
        l2.append(((x[0]-x[1])**2)**0.5)
    return l2

In [18]:
x = np.array(x)
y = np.array(y)
z = root_mean_squared_error(x,y)

In [19]:
z

[array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.]),
 array([0., 0., 0., 0., 0., 0.])]

In [7]:
x = np.random.rand(3,3)
x

array([[0.73509785, 0.35859495, 0.267241  ],
       [0.85456689, 0.66134953, 0.87256249],
       [0.26008553, 0.72212564, 0.33696628]])

In [8]:
np.amax(x)

0.8725624928077206

In [10]:
import sys
sys.maxsize

9223372036854775807

In [3]:
bikes = np.load("bikes.np.npy")

In [15]:
s = np.sum(bikes, axis=1)

In [16]:
len(s)

1440

In [17]:
cnt = 0
for i in range(len(s)):
    if s[i] == 0:
        cnt += 1
        print("%d\t" % i)
print("%d rows contain no data"%cnt)

0 rows contain no data


In [14]:
for i in range(len(s)):
    if s[i] == 0:
        bikes[i] = bikes[i-1]


In [18]:
bikes

array([[ 0, 19,  6, ...,  9, 23, 27],
       [ 0, 19,  6, ...,  9, 23, 27],
       [ 0, 19,  6, ...,  9, 23, 27],
       ...,
       [ 1,  0,  8, ...,  6, 30, 31],
       [ 1,  0,  8, ...,  6, 30, 31],
       [ 1,  0,  8, ...,  6, 30, 31]], dtype=int32)